// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TabOut
{
    internal sealed partial class Vsix
    {
        public const string Id = "TabOut.d1a2c8f6-a754-4c38-a48a-6d6ba6be4fa8";
        public const string Name = "TabOut";
        public const string Description = @"Tab out of quotes, brackets, and more. This is a port of the popular extension for VS Code";
        public const string Language = "en-US";
        public const string Version = "1.0.900";
        public const string Author = "Mads Kristensen";
        public const string Tags = "";
    }
}
